In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex=pickle.load(open("models/ohe_sex.pkl",'rb'))
ohe_embarked=pickle.load(open("models/ohe_embarked.pkl","rb"))
clf=pickle.load(open("models/clf.pkl","rb"))

In [11]:
# Asume user input
# Pclass/gender/age/Sibsp/Parch/Fare/Embarked

test_input=np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [12]:
test_input.shape

(1, 7)

In [13]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\sangw\Desktop\daily_ml\.venv311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [ ]:
test_input_sex # (0,1 ): male , (1,0): female

array([[0., 1.]])

In [16]:
test_input_embarked=ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [ ]:
test_input_embarked # for S( SouthHamtem)

array([[0., 0., 1.]])

In [19]:
test_input_age=test_input[:,2].reshape(1,1)

In [22]:
test_input_transformed=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [24]:
test_input_transformed.shape

(1, 10)

In [ ]:
clf.predict(test_input_transformed) # passanger survived

array([1])